export const BRANCH_MAP: Record<string, string> = {
    "X-01": "Xian Restaurant",
    "X-02": "Xenial Restaurant",
    "X-03": "Xiamen Restaurant",
    "X-04": "Golden Chimney Restaurant",
    "X-05": "Xindian Restaurant",
    "X-06": "Xinxian Restaurant, Dhanmondi",
    "X-07": "Four Seasons Restaurant, Dhanmondi",
    "X-08": "Xian Restaurant, Mirpur-10",
    "X-09": "Chung Wah Restaurant",
    "X-11": "Xinxian Restaurant, Uttara",
    "X-12": "Shimanto Convention Center",
    "X-16": "Xinxian Restaurant, Mirpur-01",
    "X-17": "Zam Zam Convention Center, Mirpur-01",
    "X-18": "Zam Zam Convention Center, Mirpur-11",
    "X-19": "Four Seasons Restaurant, Mirpur-11",
};
